keys1 = input("Enter the keys for dictionary1:").split(",")
values1 = input("Enter the values for dictionary1:").split(",")
dictionary1 = dict(zip(keys1, values1))
keys2 = input("Enter the keys for dictionary2:").split(",")
values2 = input("Enter the values for dictionary2:").split(",")
dictionary2 = dict(zip(keys2, values2))
merged_dict = dictionary1.copy()
merged_dict.update(dictionary2)
print(merged_dict)
